### PR TITLE
Modified app.py file: adjust the y-axis range for bar chart and removed the x-axis label

### LINKED ISSUE #49: Fix issue with numbers above bar chart in top 5 countries

### LINKED ISSUE #50: Remove country name label too

### PR DESCRIPTION
**Pull request by Jing-19**
close #49
close #50

### CODE REVIEW

**Review by jokittipong — APPROVED** [review]
Great job!!

**Comment by Jing-19** [comment]
close #46

**Comment by tangyl92** [comment]
I have break code into multiple files #52 ; I also add "check box" to the map so people can select all countries from the map #45

**Comment by Jing-19** [comment]
close #53

**Pull request merged**
