### PR TITLE
addressed comments about bar plots, pie plots and color

### PR DESCRIPTION
**Pull request by Jing-19**
Hi everyone, I have addressed feedback on: #61 #62 #63

### CODE REVIEW

**Review by jokittipong — APPROVED** [review]
LGTM!!

**Review by tangyl92 — APPROVED** [review]

**Comment by tangyl92** [comment]
Hi everyone:

I have addressed #74 #73 #64 #65

**Comment by tangyl92** [comment]
I also fixed #75

**Review by hchqin — APPROVED** [review]
Thanks!

**Pull request merged**
